# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  disable_csrf_role: ROLE_API
  body_listener: true

  view:
    view_response_listener: true

  serializer:
    serialize_null: true

  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }

  zone:
    - { path: ^/api/* }

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
