security:
  role_hierarchy:
    !php/const App\Core\Lesson\Enum\Role::ADMIN:
      - !php/const App\Core\Lesson\Enum\Role::LESSON_MANAGER
      - !php/const App\Core\Lesson\Enum\Role::OPERATOR
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_CREATE
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_UPDATE
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_DELETE
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_VALIDATION
    !php/const App\Core\Lesson\Enum\Role::MODERATOR:
      - !php/const App\Core\Lesson\Enum\Role::LESSON_MANAGER
      - !php/const App\Core\Lesson\Enum\Role::OPERATOR
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_UPDATE
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_VALIDATION
    !php/const App\Core\Lesson\Enum\Role::OPERATOR:
      - !php/const App\Core\Lesson\Enum\Role::LESSON_MANAGER
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_INDEX
    !php/const App\Core\Lesson\Enum\Role::USER:
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_SHOW
    !php/const App\Core\Lesson\Enum\Role::LESSON_MANAGER:
      - !php/const App\Core\Lesson\Enum\Role::LESSON_MANAGER
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_SHOW
      - !php/const App\Core\Lesson\Enum\Permission::LESSON_INDEX